import { createClient } from "jsr:@supabase/supabase-js@2";
const corsHeaders = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
const reply=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:corsHeaders});
function pixPayload(order:Record<string,unknown>){const tx=order.transactions as {payments?:Array<{payment_method?:Record<string,string>}>}|undefined;const m=tx?.payments?.[0]?.payment_method;return{order_id:order.id,qr_code:m?.qr_code,qr_code_base64:m?.qr_code_base64,ticket_url:m?.ticket_url};}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});if(req.method!=="POST")return reply({error:"Método não permitido"},405);
const accessToken=Deno.env.get("MERCADO_PAGO_ACCESS_TOKEN"),supabaseUrl=Deno.env.get("SUPABASE_URL"),serviceRoleKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!accessToken||!supabaseUrl||!serviceRoleKey)return reply({error:"Pagamento não configurado"},503);
const{booking_id,payment_token}=await req.json().catch(()=>({}));if(typeof booking_id!=="string"||typeof payment_token!=="string")return reply({error:"Reserva inválida"},400);
const supabase=createClient(supabaseUrl,serviceRoleKey);const{data:booking,error:bookingError}=await supabase.from("bookings").select("id,booking_code,customer_email,amount_cents,status,hold_expires_at,payment_reference,spaces(name)").eq("id",booking_id).eq("payment_token",payment_token).maybeSingle();
if(bookingError||!booking)return reply({error:"Reserva não encontrada"},404);if(booking.status!=="pending_payment"||new Date(booking.hold_expires_at)<=new Date())return reply({error:"Esta reserva expirou. Escolha outro horário."},409);
if(booking.payment_reference){const prior=await fetch(`https://api.mercadopago.com/v1/orders/${booking.payment_reference}`,{headers:{Authorization:`Bearer ${accessToken}`}});if(prior.ok)return reply(pixPayload(await prior.json()));}
const amount=(booking.amount_cents/100).toFixed(2);const response=await fetch("https://api.mercadopago.com/v1/orders",{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json",Authorization:`Bearer ${accessToken}`,"X-Idempotency-Key":`pix-${booking.id}`},body:JSON.stringify({type:"online",total_amount:amount,external_reference:booking.booking_code,processing_mode:"automatic",transactions:{payments:[{amount,payment_method:{id:"pix",type:"bank_transfer"},expiration_time:"P1D"}]},payer:{email:booking.customer_email},description:`Reserva ${(booking.spaces as {name?:string}|null)?.name||"Val Coworking"}`})});
const order=await response.json();if(!response.ok){console.error("mercado_pago_pix_error",response.status,JSON.stringify(order));return reply({error:order.message||order.cause?.[0]?.description||"Pix indisponível no Mercado Pago"},502);}
const{error:updateError}=await supabase.from("bookings").update({payment_provider:"mercado_pago",payment_reference:order.id}).eq("id",booking.id).eq("payment_token",payment_token).eq("status","pending_payment");if(updateError)return reply({error:"Não foi possível salvar o pagamento"},500);return reply(pixPayload(order),201);});
