import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const sb=createClient('https://htsnhqyhhlzqjgqlgkvt.supabase.co','sb_publishable_l1jEP6P84wREppUZwEHwSw_RRw8Ht5y');
const mercadoPagoPublicKey='APP_USR-02015adc-df8b-4c73-ae52-80796f6e4284';
const plans={fiscal_monthly:{name:'Endereço Fiscal',price:'R$ 78,00',period:'Mensal'},fiscal_annual:{name:'Endereço Fiscal',price:'R$ 698,00',period:'Anual à vista'},fiscal_biennial:{name:'Endereço Fiscal',price:'R$ 912,00',period:'Bianual à vista'},premium_monthly:{name:'Plano Premium',price:'R$ 198,00',period:'Mensal'},premium_annual:{name:'Plano Premium',price:'R$ 1.699,00',period:'Anual à vista'},premium_biennial:{name:'Plano Premium',price:'R$ 2.199,00',period:'Bianual à vista'}};
const $=id=>document.getElementById(id);const state={plan:null,application:null,widget:null};
const planDataStyle=document.createElement('style');
planDataStyle.textContent='[data-step="dados"] .selection{display:grid;gap:5px;padding:18px;border-radius:15px}[data-step="dados"] .selection small{color:#fff;font-size:15px;font-weight:700}[data-step="dados"] .selection .summary-price{text-align:left}[data-step="dados"] .form{grid-template-columns:1fr;gap:15px}[data-step="dados"] .form label{grid-column:1/-1}[data-step="dados"] .form .actions{grid-column:1/-1}';
document.head.append(planDataStyle);
const planDataPanel=document.querySelector('[data-step="dados"] .panel');
planDataPanel.querySelector('h2').textContent='Seus dados';
planDataPanel.querySelector('.eyebrow + h2 + p').textContent='Vamos usar estes dados para confirmar seu plano.';
const planForm=$('plan-form'),planStatus=$('form-status');
['name','email','phone','company','document','address'].forEach(name=>{const label=planForm.elements[name].closest('label');label.classList.remove('full');planForm.insertBefore(label,planStatus);});
planForm.elements.address.closest('label').firstChild.textContent='Endereço atual';
function go(step){document.querySelectorAll('.step').forEach(el=>el.classList.toggle('active',el.dataset.step===step));const index=['plano','dados','contrato','pagamento'].indexOf(step);document.querySelectorAll('.progress i').forEach((el,i)=>el.classList.toggle('active',i<=index));history.replaceState({},'',`?etapa=${step}`);window.scrollTo({top:0,behavior:'smooth'});}
function alert(message){const el=$('notice');el.textContent=message;el.hidden=!message;}
function paymentMessage(message,kind='notice'){$('payment-status').className=kind;$('payment-status').textContent=message;$('payment-status').hidden=!message;}
async function appRequest(action,body={}){const{data,error}=await sb.functions.invoke('plan-payment',{body:{application_id:state.application.id,access_token:state.application.access_token,action,...body}});if(error){const detail=await error.context?.json?.().catch(()=>null);throw new Error(detail?.error||error.message||'Não foi possível processar o pagamento.');}if(data?.error)throw new Error(data.error);return data;}
document.querySelectorAll('[data-plan]').forEach(button=>button.onclick=()=>{state.plan=button.dataset.plan;document.querySelectorAll('[data-plan]').forEach(el=>el.classList.toggle('active',el===button));alert('');});
$('continue-plan').onclick=()=>{if(!state.plan)return alert('Escolha um plano para continuar.');const p=plans[state.plan];$('plan-summary').innerHTML=`<div><span class="summary-label">Plano selecionado</span><strong>${p.name}</strong><small>${p.period}</small></div><span class="summary-price">${p.price}</span>`;go('dados');};
document.querySelectorAll('[data-back]').forEach(button=>button.onclick=()=>go(button.dataset.back));
async function signature(action){const{data,error}=await sb.functions.invoke('clicksign-plan-signature',{body:{application_id:state.application.id,access_token:state.application.access_token,action}});if(error){const details=await error.context?.json?.().catch(()=>null);throw new Error(details?.error||error.message||'Não foi possível acessar a assinatura digital.');}if(data?.error)throw new Error(data.error);return data;}
function contractMessage(title,text,kind=''){$('contract-content').innerHTML=`<span class="contract-icon"><i class="ph ph-file-text"></i></span><h3>${title}</h3><p>${text}</p>${kind?`<p class="${kind}">Pagamento bloqueado até o contrato ser assinado.</p>`:''}`;}
function loadWidget(){return new Promise((resolve,reject)=>{if(window.Clicksign)return resolve();const script=document.createElement('script');script.src='https://cdn-public-library.clicksign.com/embedded/embedded.min-2.1.0.js';script.onload=resolve;script.onerror=()=>reject(new Error('Não foi possível carregar a assinatura digital.'));document.body.append(script);});}
function renderPayment(){const p=plans[state.application.plan_key]||plans[state.plan];$('payment-summary').innerHTML=`<div><span class="summary-label">Plano contratado</span><strong>${state.application.plan_name||p.name}</strong><small>${state.application.billing_label||p.period}</small></div><span class="summary-price">R$ ${Number(state.application.amount_cents/100).toLocaleString('pt-BR',{minimumFractionDigits:2})}</span>`;}
async function showSigned(){contractMessage('Contrato assinado','Sua assinatura foi validada. Agora escolha a forma de pagamento.');renderPayment();go('pagamento');}
async function verifySignature(){contractMessage('Validando assinatura…','Estamos confirmando a assinatura diretamente com a Clicksign.');try{const result=await signature('status');if(result.signed)return showSigned();contractMessage('Assinatura pendente','Conclua a assinatura no formulário acima. Se você já assinou, aguarde alguns segundos e tente novamente.','success');$('contract-actions').innerHTML='<button id="check-signature" class="button primary">Verificar assinatura <i class="ph ph-check"></i></button>';$('check-signature').onclick=verifySignature;}catch(error){contractMessage('Não foi possível validar',error.message);}}
async function mountSignature(){contractMessage(`Contrato ${state.application.request_code}`,'Preparando o contrato para assinatura…');go('contrato');try{const result=await signature('create');if(result.signed)return showSigned();if(result.environment==='production'&&window.location.protocol!=='https:'){$('contract-content').innerHTML='<div class="signature-head"><span class="contract-icon"><i class="ph ph-lock-key"></i></span><div><h3>Assinatura disponível no site seguro</h3><p>A Clicksign exige HTTPS para mostrar a assinatura dentro da página. Abra esta etapa pelo site publicado.</p></div></div>';$('contract-actions').innerHTML='';return;}await loadWidget();$('contract-content').innerHTML='<div class="signature-head"><span class="contract-icon"><i class="ph ph-signature"></i></span><div><h3>Assine seu contrato</h3><p>Confirme sua identidade por e-mail e conclua a assinatura abaixo.</p></div></div><div id="clicksign-widget" class="clicksign-widget" aria-label="Assinatura digital"></div>';if(state.widget)state.widget.unmount();state.widget=new window.Clicksign(result.signer_id);state.widget.endpoint=result.environment==='production'?'https://app.clicksign.com':'https://sandbox.clicksign.com';state.widget.origin=window.location.origin;state.widget.mount('clicksign-widget');state.widget.on('resized',event=>{$('clicksign-widget').style.height=`${Math.max(520,event.data.height)}px`;});state.widget.on('signed',()=>setTimeout(verifySignature,1200));$('contract-actions').innerHTML='<button id="check-signature" class="button">Já assinei — verificar <i class="ph ph-check"></i></button>';$('check-signature').onclick=verifySignature;}catch(error){contractMessage('Contrato indisponível',error.message);}}
async function createPix(){const button=$('pay-pix');button.disabled=true;paymentMessage('Gerando Pix…','success');try{const data=await appRequest('pix');if(!data.qr_code_base64)throw new Error('O Mercado Pago não retornou o QR Code.');$('pix-area').hidden=false;$('pix-area').innerHTML=`<img alt="QR Code Pix" src="data:image/png;base64,${data.qr_code_base64}"/><strong>Escaneie o QR Code ou copie o código Pix</strong><code>${data.qr_code}</code><button id="copy-pix" class="button">Copiar código <i class="ph ph-copy"></i></button>`;$('copy-pix').onclick=async()=>{await navigator.clipboard.writeText(data.qr_code);$('copy-pix').textContent='Código copiado';};paymentMessage('Pix gerado. A confirmação ocorre automaticamente após o pagamento.','success');}catch(error){paymentMessage(error.message);}finally{button.disabled=false;}}
async function loadMercadoPagoSdk(){if(window.MercadoPago)return;await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://sdk.mercadopago.com/js/v2';script.onload=resolve;script.onerror=()=>reject(new Error('Não foi possível carregar o cartão.'));document.body.appendChild(script);});}
async function openCardPayment(){try{await loadMercadoPagoSdk();const area=$('card-payment-area');area.hidden=false;window.planCardController?.unmount();const mp=new window.MercadoPago(mercadoPagoPublicKey,{locale:'pt-BR'});window.planCardController=await mp.bricks().create('cardPayment','card-payment-area',{initialization:{amount:state.application.amount_cents/100},callbacks:{onSubmit:(formData,additionalData)=>new Promise(async(resolve,reject)=>{try{const data=await appRequest('card',{card_token:formData.token,payment_method_id:formData.payment_method_id,payment_type:additionalData.paymentTypeId,installments:formData.installments});paymentMessage(data.paid?'Pagamento aprovado.':'Pagamento em processamento.','success');resolve();}catch(error){paymentMessage(error.message);reject();}}),onError:error=>paymentMessage(error.message||'Não foi possível abrir o cartão.')}});}catch(error){paymentMessage(error.message);}}
$('pay-pix').onclick=createPix;$('pay-card').onclick=openCardPayment;
function formError(input,message){const status=$('form-status');document.querySelectorAll('#plan-form input.invalid').forEach(field=>{field.classList.remove('invalid');field.removeAttribute('aria-invalid');});input.classList.add('invalid');input.setAttribute('aria-invalid','true');status.hidden=false;status.textContent=message;input.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>input.focus({preventScroll:true}),250);}
function clearFormError(input){input.classList.remove('invalid');input.removeAttribute('aria-invalid');}
function validPlanForm(form){const name=form.elements.name,email=form.elements.email,phone=form.elements.phone,company=form.elements.company,address=form.elements.address,documentInput=form.elements.document;const phoneDigits=phone.value.replace(/\D/g,''),documentNumber=documentInput.value.replace(/\D/g,'');if(name.value.trim().length<3)return formError(name,'Revise o campo Nome completo.'),false;if(!email.validity.valid)return formError(email,'Informe um e-mail válido.'),false;if(!/^\d{10,11}$/.test(phoneDigits))return formError(phone,'Informe um telefone com DDD.'),false;if(company.value.trim().length<2)return formError(company,'Informe o nome da empresa.'),false;if(address.value.trim().length<8)return formError(address,'Informe o endereço completo da contratante.'),false;if(!/^\d{11}$|^\d{14}$/.test(documentNumber))return formError(documentInput,'Informe um CPF (11 dígitos) ou CNPJ (14 dígitos) válido.'),false;return true;}
$('plan-form').querySelectorAll('input').forEach(input=>input.addEventListener('input',()=>clearFormError(input)));
$('plan-form').onsubmit=async event=>{event.preventDefault();const formElement=event.currentTarget;if(!validPlanForm(formElement))return;const button=event.submitter||formElement.querySelector('[type="submit"]'),form=new FormData(formElement),documentNumber=String(form.get('document')||'').replace(/\D/g,''),address=String(form.get('address')||'').trim();button.disabled=true;$('form-status').hidden=false;$('form-status').textContent='Registrando sua solicitação…';const{data,error}=await sb.rpc('create_plan_application',{p_plan_key:state.plan,p_customer_name:form.get('name'),p_customer_email:form.get('email'),p_customer_phone:form.get('phone'),p_company_name:form.get('company'),p_customer_address:address,p_customer_document:documentNumber});button.disabled=false;if(error){$('form-status').textContent=error.message;return;}state.application=data?.[0];if(!state.application){$('form-status').textContent='Não foi possível iniciar o contrato.';return;}sessionStorage.setItem('val-coworking-plan',JSON.stringify(state.application));mountSignature();};
try{const saved=JSON.parse(sessionStorage.getItem('val-coworking-plan'));if(saved)state.application=saved;}catch{}
